[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_URL = "https://bizmanage-api.onrender.com"

[[redirects]]
  from = "/api/*"
  to = "https://bizmanage-api.onrender.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
